/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ItemType = IDL.Variant({
  'Weapon' : IDL.Null,
  'Potion' : IDL.Null,
  'Misc' : IDL.Null,
  'Armor' : IDL.Null,
});
export const StatBonus = IDL.Record({
  'hp' : IDL.Int,
  'mp' : IDL.Int,
  'speed' : IDL.Int,
  'defense' : IDL.Int,
  'attack' : IDL.Int,
});
export const Item = IDL.Record({
  'id' : IDL.Nat,
  'statBonus' : StatBonus,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'equipped' : IDL.Bool,
  'itemType' : ItemType,
  'quantity' : IDL.Nat,
});
export const ItemResult = IDL.Record({
  'item' : IDL.Opt(Item),
  'narration' : IDL.Text,
  'success' : IDL.Bool,
});
export const QuestStatus = IDL.Variant({
  'Available' : IDL.Null,
  'Active' : IDL.Null,
  'Completed' : IDL.Null,
});
export const Objective = IDL.Record({
  'text' : IDL.Text,
  'completed' : IDL.Bool,
});
export const Quest = IDL.Record({
  'id' : IDL.Nat,
  'status' : QuestStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'rewards' : IDL.Record({
    'xp' : IDL.Nat,
    'gold' : IDL.Nat,
    'items' : IDL.Vec(Item),
  }),
  'objectives' : IDL.Vec(Objective),
});
export const QuestResult = IDL.Record({
  'quest' : IDL.Opt(Quest),
  'narration' : IDL.Text,
  'success' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CombatResult = IDL.Record({
  'playerAction' : IDL.Text,
  'playerHp' : IDL.Nat,
  'xpGained' : IDL.Nat,
  'leveledUp' : IDL.Bool,
  'narration' : IDL.Text,
  'goldGained' : IDL.Nat,
  'success' : IDL.Bool,
  'enemyHp' : IDL.Nat,
  'enemyAction' : IDL.Text,
});
export const Race = IDL.Variant({
  'Elf' : IDL.Null,
  'Orc' : IDL.Null,
  'Dwarf' : IDL.Null,
  'Human' : IDL.Null,
});
export const Class = IDL.Variant({
  'Mage' : IDL.Null,
  'Cleric' : IDL.Null,
  'Rogue' : IDL.Null,
  'Warrior' : IDL.Null,
});
export const Zone = IDL.Variant({
  'Forest' : IDL.Null,
  'Town' : IDL.Null,
  'Mountains' : IDL.Null,
  'Dungeon' : IDL.Null,
  'Castle' : IDL.Null,
});
export const Character = IDL.Record({
  'hp' : IDL.Nat,
  'mp' : IDL.Nat,
  'xp' : IDL.Nat,
  'charClass' : Class,
  'maxHp' : IDL.Nat,
  'maxMp' : IDL.Nat,
  'gold' : IDL.Nat,
  'inventory' : IDL.Vec(Item),
  'name' : IDL.Text,
  'race' : Race,
  'zone' : Zone,
  'level' : IDL.Nat,
  'speed' : IDL.Nat,
  'defense' : IDL.Nat,
  'xpToNext' : IDL.Nat,
  'backstory' : IDL.Text,
  'quests' : IDL.Vec(Quest),
  'attack' : IDL.Nat,
});
export const CreateCharacterResult = IDL.Record({
  'character' : IDL.Opt(Character),
  'narration' : IDL.Text,
  'success' : IDL.Bool,
});
export const ExplorationResult = IDL.Record({
  'loot' : IDL.Opt(IDL.Vec(Item)),
  'zone' : Zone,
  'xpGained' : IDL.Nat,
  'narration' : IDL.Text,
  'goldGained' : IDL.Nat,
  'success' : IDL.Bool,
  'encounter' : IDL.Opt(IDL.Text),
});
export const ActiveCombat = IDL.Record({
  'maxHp' : IDL.Nat,
  'enemyName' : IDL.Text,
  'enemyHp' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'characterCreated' : IDL.Bool,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'read' : IDL.Bool,
  'toPrincipal' : IDL.Principal,
  'fromPrincipal' : IDL.Principal,
  'timestamp' : IDL.Int,
  'fromName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptQuest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'addItem' : IDL.Func(
      [IDL.Nat, IDL.Text, ItemType, IDL.Text, StatBonus],
      [ItemResult],
      [],
    ),
  'addQuest' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [QuestResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'attack' : IDL.Func([], [CombatResult], []),
  'attackEnemy' : IDL.Func([], [CombatResult], []),
  'createCharacter' : IDL.Func(
      [IDL.Text, Race, Class],
      [CreateCharacterResult],
      [],
    ),
  'equipItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'explore' : IDL.Func([], [ExplorationResult], []),
  'exploreZone' : IDL.Func([Zone], [ExplorationResult], []),
  'fleeCombat' : IDL.Func([], [IDL.Bool], []),
  'getActiveCombat' : IDL.Func([], [IDL.Opt(ActiveCombat)], ['query']),
  'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharacter' : IDL.Func([], [Character], ['query']),
  'getInbox' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getInventory' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getItemsById' : IDL.Func([IDL.Nat], [IDL.Vec(Item)], ['query']),
  'getQuests' : IDL.Func([], [IDL.Vec(Quest)], ['query']),
  'getQuestsByStatus' : IDL.Func([QuestStatus], [IDL.Vec(Quest)], ['query']),
  'getSentMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessageRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
  'startCombat' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'travelToZone' : IDL.Func([Zone], [IDL.Bool], []),
  'usePotion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ItemType = IDL.Variant({
    'Weapon' : IDL.Null,
    'Potion' : IDL.Null,
    'Misc' : IDL.Null,
    'Armor' : IDL.Null,
  });
  const StatBonus = IDL.Record({
    'hp' : IDL.Int,
    'mp' : IDL.Int,
    'speed' : IDL.Int,
    'defense' : IDL.Int,
    'attack' : IDL.Int,
  });
  const Item = IDL.Record({
    'id' : IDL.Nat,
    'statBonus' : StatBonus,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'equipped' : IDL.Bool,
    'itemType' : ItemType,
    'quantity' : IDL.Nat,
  });
  const ItemResult = IDL.Record({
    'item' : IDL.Opt(Item),
    'narration' : IDL.Text,
    'success' : IDL.Bool,
  });
  const QuestStatus = IDL.Variant({
    'Available' : IDL.Null,
    'Active' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const Objective = IDL.Record({ 'text' : IDL.Text, 'completed' : IDL.Bool });
  const Quest = IDL.Record({
    'id' : IDL.Nat,
    'status' : QuestStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'rewards' : IDL.Record({
      'xp' : IDL.Nat,
      'gold' : IDL.Nat,
      'items' : IDL.Vec(Item),
    }),
    'objectives' : IDL.Vec(Objective),
  });
  const QuestResult = IDL.Record({
    'quest' : IDL.Opt(Quest),
    'narration' : IDL.Text,
    'success' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CombatResult = IDL.Record({
    'playerAction' : IDL.Text,
    'playerHp' : IDL.Nat,
    'xpGained' : IDL.Nat,
    'leveledUp' : IDL.Bool,
    'narration' : IDL.Text,
    'goldGained' : IDL.Nat,
    'success' : IDL.Bool,
    'enemyHp' : IDL.Nat,
    'enemyAction' : IDL.Text,
  });
  const Race = IDL.Variant({
    'Elf' : IDL.Null,
    'Orc' : IDL.Null,
    'Dwarf' : IDL.Null,
    'Human' : IDL.Null,
  });
  const Class = IDL.Variant({
    'Mage' : IDL.Null,
    'Cleric' : IDL.Null,
    'Rogue' : IDL.Null,
    'Warrior' : IDL.Null,
  });
  const Zone = IDL.Variant({
    'Forest' : IDL.Null,
    'Town' : IDL.Null,
    'Mountains' : IDL.Null,
    'Dungeon' : IDL.Null,
    'Castle' : IDL.Null,
  });
  const Character = IDL.Record({
    'hp' : IDL.Nat,
    'mp' : IDL.Nat,
    'xp' : IDL.Nat,
    'charClass' : Class,
    'maxHp' : IDL.Nat,
    'maxMp' : IDL.Nat,
    'gold' : IDL.Nat,
    'inventory' : IDL.Vec(Item),
    'name' : IDL.Text,
    'race' : Race,
    'zone' : Zone,
    'level' : IDL.Nat,
    'speed' : IDL.Nat,
    'defense' : IDL.Nat,
    'xpToNext' : IDL.Nat,
    'backstory' : IDL.Text,
    'quests' : IDL.Vec(Quest),
    'attack' : IDL.Nat,
  });
  const CreateCharacterResult = IDL.Record({
    'character' : IDL.Opt(Character),
    'narration' : IDL.Text,
    'success' : IDL.Bool,
  });
  const ExplorationResult = IDL.Record({
    'loot' : IDL.Opt(IDL.Vec(Item)),
    'zone' : Zone,
    'xpGained' : IDL.Nat,
    'narration' : IDL.Text,
    'goldGained' : IDL.Nat,
    'success' : IDL.Bool,
    'encounter' : IDL.Opt(IDL.Text),
  });
  const ActiveCombat = IDL.Record({
    'maxHp' : IDL.Nat,
    'enemyName' : IDL.Text,
    'enemyHp' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'characterCreated' : IDL.Bool,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'read' : IDL.Bool,
    'toPrincipal' : IDL.Principal,
    'fromPrincipal' : IDL.Principal,
    'timestamp' : IDL.Int,
    'fromName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptQuest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'addItem' : IDL.Func(
        [IDL.Nat, IDL.Text, ItemType, IDL.Text, StatBonus],
        [ItemResult],
        [],
      ),
    'addQuest' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [QuestResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'attack' : IDL.Func([], [CombatResult], []),
    'attackEnemy' : IDL.Func([], [CombatResult], []),
    'createCharacter' : IDL.Func(
        [IDL.Text, Race, Class],
        [CreateCharacterResult],
        [],
      ),
    'equipItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'explore' : IDL.Func([], [ExplorationResult], []),
    'exploreZone' : IDL.Func([Zone], [ExplorationResult], []),
    'fleeCombat' : IDL.Func([], [IDL.Bool], []),
    'getActiveCombat' : IDL.Func([], [IDL.Opt(ActiveCombat)], ['query']),
    'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharacter' : IDL.Func([], [Character], ['query']),
    'getInbox' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getInventory' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getItemsById' : IDL.Func([IDL.Nat], [IDL.Vec(Item)], ['query']),
    'getQuests' : IDL.Func([], [IDL.Vec(Quest)], ['query']),
    'getQuestsByStatus' : IDL.Func([QuestStatus], [IDL.Vec(Quest)], ['query']),
    'getSentMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessageRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
    'startCombat' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'travelToZone' : IDL.Func([Zone], [IDL.Bool], []),
    'usePotion' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };