/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActiveCombat {
  'maxHp' : bigint,
  'enemyName' : string,
  'enemyHp' : bigint,
}
export interface Character {
  'hp' : bigint,
  'mp' : bigint,
  'xp' : bigint,
  'charClass' : Class,
  'maxHp' : bigint,
  'maxMp' : bigint,
  'gold' : bigint,
  'inventory' : Array<Item>,
  'name' : string,
  'race' : Race,
  'zone' : Zone,
  'level' : bigint,
  'speed' : bigint,
  'defense' : bigint,
  'xpToNext' : bigint,
  'backstory' : string,
  'quests' : Array<Quest>,
  'attack' : bigint,
}
export type Class = { 'Mage' : null } |
  { 'Cleric' : null } |
  { 'Rogue' : null } |
  { 'Warrior' : null };
export interface CombatResult {
  'playerAction' : string,
  'playerHp' : bigint,
  'xpGained' : bigint,
  'leveledUp' : boolean,
  'narration' : string,
  'goldGained' : bigint,
  'success' : boolean,
  'enemyHp' : bigint,
  'enemyAction' : string,
}
export interface CreateCharacterResult {
  'character' : [] | [Character],
  'narration' : string,
  'success' : boolean,
}
export interface ExplorationResult {
  'loot' : [] | [Array<Item>],
  'zone' : Zone,
  'xpGained' : bigint,
  'narration' : string,
  'goldGained' : bigint,
  'success' : boolean,
  'encounter' : [] | [string],
}
export interface Item {
  'id' : bigint,
  'statBonus' : StatBonus,
  'name' : string,
  'description' : string,
  'equipped' : boolean,
  'itemType' : ItemType,
  'quantity' : bigint,
}
export interface ItemResult {
  'item' : [] | [Item],
  'narration' : string,
  'success' : boolean,
}
export type ItemType = { 'Weapon' : null } |
  { 'Potion' : null } |
  { 'Misc' : null } |
  { 'Armor' : null };
export interface Message {
  'id' : bigint,
  'content' : string,
  'read' : boolean,
  'toPrincipal' : Principal,
  'fromPrincipal' : Principal,
  'timestamp' : bigint,
  'fromName' : string,
}
export interface Objective { 'text' : string, 'completed' : boolean }
export interface Quest {
  'id' : bigint,
  'status' : QuestStatus,
  'title' : string,
  'description' : string,
  'rewards' : { 'xp' : bigint, 'gold' : bigint, 'items' : Array<Item> },
  'objectives' : Array<Objective>,
}
export interface QuestResult {
  'quest' : [] | [Quest],
  'narration' : string,
  'success' : boolean,
}
export type QuestStatus = { 'Available' : null } |
  { 'Active' : null } |
  { 'Completed' : null };
export type Race = { 'Elf' : null } |
  { 'Orc' : null } |
  { 'Dwarf' : null } |
  { 'Human' : null };
export interface StatBonus {
  'hp' : bigint,
  'mp' : bigint,
  'speed' : bigint,
  'defense' : bigint,
  'attack' : bigint,
}
export interface UserProfile { 'name' : string, 'characterCreated' : boolean }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Zone = { 'Forest' : null } |
  { 'Town' : null } |
  { 'Mountains' : null } |
  { 'Dungeon' : null } |
  { 'Castle' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptQuest' : ActorMethod<[bigint], boolean>,
  'addItem' : ActorMethod<
    [bigint, string, ItemType, string, StatBonus],
    ItemResult
  >,
  'addQuest' : ActorMethod<[bigint, string, string], QuestResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'attack' : ActorMethod<[], CombatResult>,
  'attackEnemy' : ActorMethod<[], CombatResult>,
  'createCharacter' : ActorMethod<[string, Race, Class], CreateCharacterResult>,
  'equipItem' : ActorMethod<[bigint], boolean>,
  'explore' : ActorMethod<[], ExplorationResult>,
  'exploreZone' : ActorMethod<[Zone], ExplorationResult>,
  'fleeCombat' : ActorMethod<[], boolean>,
  'getActiveCombat' : ActorMethod<[], [] | [ActiveCombat]>,
  'getAllCharacters' : ActorMethod<[], Array<Character>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCharacter' : ActorMethod<[], Character>,
  'getInbox' : ActorMethod<[], Array<Message>>,
  'getInventory' : ActorMethod<[], Array<Item>>,
  'getItemsById' : ActorMethod<[bigint], Array<Item>>,
  'getQuests' : ActorMethod<[], Array<Quest>>,
  'getQuestsByStatus' : ActorMethod<[QuestStatus], Array<Quest>>,
  'getSentMessages' : ActorMethod<[], Array<Message>>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessageRead' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], boolean>,
  'startCombat' : ActorMethod<[string, bigint], boolean>,
  'travelToZone' : ActorMethod<[Zone], boolean>,
  'usePotion' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];