/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ExplorationResult {
    loot?: Array<Item>;
    zone: Zone;
    xpGained: bigint;
    narration: string;
    goldGained: bigint;
    success: boolean;
    encounter?: string;
}
export interface ActiveCombat {
    maxHp: bigint;
    enemyName: string;
    enemyHp: bigint;
}
export interface QuestResult {
    quest?: Quest;
    narration: string;
    success: boolean;
}
export interface StatBonus {
    hp: bigint;
    mp: bigint;
    speed: bigint;
    defense: bigint;
    attack: bigint;
}
export interface ItemResult {
    item?: Item;
    narration: string;
    success: boolean;
}
export interface Character {
    hp: bigint;
    mp: bigint;
    xp: bigint;
    charClass: Class;
    maxHp: bigint;
    maxMp: bigint;
    gold: bigint;
    inventory: Array<Item>;
    name: string;
    race: Race;
    zone: Zone;
    level: bigint;
    speed: bigint;
    defense: bigint;
    xpToNext: bigint;
    backstory: string;
    quests: Array<Quest>;
    attack: bigint;
}
export interface Item {
    id: bigint;
    statBonus: StatBonus;
    name: string;
    description: string;
    equipped: boolean;
    itemType: ItemType;
    quantity: bigint;
}
export interface CreateCharacterResult {
    character?: Character;
    narration: string;
    success: boolean;
}
export interface Message {
    id: bigint;
    content: string;
    read: boolean;
    toPrincipal: Principal;
    fromPrincipal: Principal;
    timestamp: bigint;
    fromName: string;
}
export interface Quest {
    id: bigint;
    status: QuestStatus;
    title: string;
    description: string;
    rewards: {
        xp: bigint;
        gold: bigint;
        items: Array<Item>;
    };
    objectives: Array<Objective>;
}
export interface CombatResult {
    playerAction: string;
    playerHp: bigint;
    xpGained: bigint;
    leveledUp: boolean;
    narration: string;
    goldGained: bigint;
    success: boolean;
    enemyHp: bigint;
    enemyAction: string;
}
export interface Objective {
    text: string;
    completed: boolean;
}
export interface UserProfile {
    name: string;
    characterCreated: boolean;
}
export enum Class {
    Mage = "Mage",
    Cleric = "Cleric",
    Rogue = "Rogue",
    Warrior = "Warrior"
}
export enum ItemType {
    Weapon = "Weapon",
    Potion = "Potion",
    Misc = "Misc",
    Armor = "Armor"
}
export enum QuestStatus {
    Available = "Available",
    Active = "Active",
    Completed = "Completed"
}
export enum Race {
    Elf = "Elf",
    Orc = "Orc",
    Dwarf = "Dwarf",
    Human = "Human"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Zone {
    Forest = "Forest",
    Town = "Town",
    Mountains = "Mountains",
    Dungeon = "Dungeon",
    Castle = "Castle"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptQuest(questId: bigint): Promise<boolean>;
    addItem(id: bigint, name: string, itemType: ItemType, description: string, statBonus: StatBonus): Promise<ItemResult>;
    addQuest(id: bigint, title: string, description: string): Promise<QuestResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    attack(): Promise<CombatResult>;
    attackEnemy(): Promise<CombatResult>;
    createCharacter(name: string, race: Race, charClass: Class): Promise<CreateCharacterResult>;
    equipItem(itemId: bigint): Promise<boolean>;
    explore(): Promise<ExplorationResult>;
    exploreZone(zone: Zone): Promise<ExplorationResult>;
    fleeCombat(): Promise<boolean>;
    getActiveCombat(): Promise<ActiveCombat | null>;
    getAllCharacters(): Promise<Array<Character>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCharacter(): Promise<Character>;
    getInbox(): Promise<Array<Message>>;
    getInventory(): Promise<Array<Item>>;
    getItemsById(id: bigint): Promise<Array<Item>>;
    getQuests(): Promise<Array<Quest>>;
    getQuestsByStatus(status: QuestStatus): Promise<Array<Quest>>;
    getSentMessages(): Promise<Array<Message>>;
    getUnreadCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markMessageRead(messageId: bigint): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(toPrincipal: Principal, content: string): Promise<boolean>;
    startCombat(enemyName: string, enemyHp: bigint): Promise<boolean>;
    travelToZone(zone: Zone): Promise<boolean>;
    usePotion(itemId: bigint): Promise<boolean>;
}
import type { ActiveCombat as _ActiveCombat, Character as _Character, Class as _Class, CreateCharacterResult as _CreateCharacterResult, ExplorationResult as _ExplorationResult, Item as _Item, ItemResult as _ItemResult, ItemType as _ItemType, Objective as _Objective, Quest as _Quest, QuestResult as _QuestResult, QuestStatus as _QuestStatus, Race as _Race, StatBonus as _StatBonus, UserProfile as _UserProfile, UserRole as _UserRole, Zone as _Zone } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptQuest(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptQuest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptQuest(arg0);
            return result;
        }
    }
    async addItem(arg0: bigint, arg1: string, arg2: ItemType, arg3: string, arg4: StatBonus): Promise<ItemResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addItem(arg0, arg1, to_candid_ItemType_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return from_candid_ItemResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItem(arg0, arg1, to_candid_ItemType_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return from_candid_ItemResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addQuest(arg0: bigint, arg1: string, arg2: string): Promise<QuestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuest(arg0, arg1, arg2);
                return from_candid_QuestResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuest(arg0, arg1, arg2);
            return from_candid_QuestResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async attack(): Promise<CombatResult> {
        if (this.processError) {
            try {
                const result = await this.actor.attack();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.attack();
            return result;
        }
    }
    async attackEnemy(): Promise<CombatResult> {
        if (this.processError) {
            try {
                const result = await this.actor.attackEnemy();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.attackEnemy();
            return result;
        }
    }
    async createCharacter(arg0: string, arg1: Race, arg2: Class): Promise<CreateCharacterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createCharacter(arg0, to_candid_Race_n21(this._uploadFile, this._downloadFile, arg1), to_candid_Class_n23(this._uploadFile, this._downloadFile, arg2));
                return from_candid_CreateCharacterResult_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCharacter(arg0, to_candid_Race_n21(this._uploadFile, this._downloadFile, arg1), to_candid_Class_n23(this._uploadFile, this._downloadFile, arg2));
            return from_candid_CreateCharacterResult_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async equipItem(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.equipItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.equipItem(arg0);
            return result;
        }
    }
    async explore(): Promise<ExplorationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.explore();
                return from_candid_ExplorationResult_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.explore();
            return from_candid_ExplorationResult_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async exploreZone(arg0: Zone): Promise<ExplorationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.exploreZone(to_candid_Zone_n41(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ExplorationResult_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exploreZone(to_candid_Zone_n41(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ExplorationResult_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async fleeCombat(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.fleeCombat();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fleeCombat();
            return result;
        }
    }
    async getActiveCombat(): Promise<ActiveCombat | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveCombat();
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveCombat();
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCharacters(): Promise<Array<Character>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCharacters();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCharacters();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCharacter(): Promise<Character> {
        if (this.processError) {
            try {
                const result = await this.actor.getCharacter();
                return from_candid_Character_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCharacter();
            return from_candid_Character_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInbox(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInbox();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInbox();
            return result;
        }
    }
    async getInventory(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventory();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventory();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItemsById(arg0: bigint): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemsById(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemsById(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuests(): Promise<Array<Quest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuests();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuests();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestsByStatus(arg0: QuestStatus): Promise<Array<Quest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestsByStatus(to_candid_QuestStatus_n48(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestsByStatus(to_candid_QuestStatus_n48(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSentMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSentMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSentMessages();
            return result;
        }
    }
    async getUnreadCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markMessageRead(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageRead(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async startCombat(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.startCombat(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startCombat(arg0, arg1);
            return result;
        }
    }
    async travelToZone(arg0: Zone): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.travelToZone(to_candid_Zone_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.travelToZone(to_candid_Zone_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async usePotion(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.usePotion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.usePotion(arg0);
            return result;
        }
    }
}
function from_candid_Character_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Character): Character {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Class_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Class): Class {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_CreateCharacterResult_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateCharacterResult): CreateCharacterResult {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_ExplorationResult_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExplorationResult): ExplorationResult {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ItemResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemResult): ItemResult {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ItemType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemType): ItemType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Item_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Item): Item {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_QuestResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestResult): QuestResult {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_QuestStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestStatus): QuestStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Quest_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quest): Quest {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Race_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Race): Race {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Zone_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Zone): Zone {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quest]): Quest | null {
    return value.length === 0 ? null : from_candid_Quest_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Character]): Character | null {
    return value.length === 0 ? null : from_candid_Character_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Item>]): Array<Item> | null {
    return value.length === 0 ? null : from_candid_vec_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ActiveCombat]): ActiveCombat | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Item]): Item | null {
    return value.length === 0 ? null : from_candid_Item_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quest: [] | [_Quest];
    narration: string;
    success: boolean;
}): {
    quest?: Quest;
    narration: string;
    success: boolean;
} {
    return {
        quest: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.quest)),
        narration: value.narration,
        success: value.success
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _QuestStatus;
    title: string;
    description: string;
    rewards: {
        xp: bigint;
        gold: bigint;
        items: Array<_Item>;
    };
    objectives: Array<_Objective>;
}): {
    id: bigint;
    status: QuestStatus;
    title: string;
    description: string;
    rewards: {
        xp: bigint;
        gold: bigint;
        items: Array<Item>;
    };
    objectives: Array<Objective>;
} {
    return {
        id: value.id,
        status: from_candid_QuestStatus_n15(_uploadFile, _downloadFile, value.status),
        title: value.title,
        description: value.description,
        rewards: from_candid_record_n17(_uploadFile, _downloadFile, value.rewards),
        objectives: value.objectives
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    gold: bigint;
    items: Array<_Item>;
}): {
    xp: bigint;
    gold: bigint;
    items: Array<Item>;
} {
    return {
        xp: value.xp,
        gold: value.gold,
        items: from_candid_vec_n18(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    character: [] | [_Character];
    narration: string;
    success: boolean;
}): {
    character?: Character;
    narration: string;
    success: boolean;
} {
    return {
        character: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.character)),
        narration: value.narration,
        success: value.success
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hp: bigint;
    mp: bigint;
    xp: bigint;
    charClass: _Class;
    maxHp: bigint;
    maxMp: bigint;
    gold: bigint;
    inventory: Array<_Item>;
    name: string;
    race: _Race;
    zone: _Zone;
    level: bigint;
    speed: bigint;
    defense: bigint;
    xpToNext: bigint;
    backstory: string;
    quests: Array<_Quest>;
    attack: bigint;
}): {
    hp: bigint;
    mp: bigint;
    xp: bigint;
    charClass: Class;
    maxHp: bigint;
    maxMp: bigint;
    gold: bigint;
    inventory: Array<Item>;
    name: string;
    race: Race;
    zone: Zone;
    level: bigint;
    speed: bigint;
    defense: bigint;
    xpToNext: bigint;
    backstory: string;
    quests: Array<Quest>;
    attack: bigint;
} {
    return {
        hp: value.hp,
        mp: value.mp,
        xp: value.xp,
        charClass: from_candid_Class_n30(_uploadFile, _downloadFile, value.charClass),
        maxHp: value.maxHp,
        maxMp: value.maxMp,
        gold: value.gold,
        inventory: from_candid_vec_n18(_uploadFile, _downloadFile, value.inventory),
        name: value.name,
        race: from_candid_Race_n32(_uploadFile, _downloadFile, value.race),
        zone: from_candid_Zone_n34(_uploadFile, _downloadFile, value.zone),
        level: value.level,
        speed: value.speed,
        defense: value.defense,
        xpToNext: value.xpToNext,
        backstory: value.backstory,
        quests: from_candid_vec_n36(_uploadFile, _downloadFile, value.quests),
        attack: value.attack
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    loot: [] | [Array<_Item>];
    zone: _Zone;
    xpGained: bigint;
    narration: string;
    goldGained: bigint;
    success: boolean;
    encounter: [] | [string];
}): {
    loot?: Array<Item>;
    zone: Zone;
    xpGained: bigint;
    narration: string;
    goldGained: bigint;
    success: boolean;
    encounter?: string;
} {
    return {
        loot: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.loot)),
        zone: from_candid_Zone_n34(_uploadFile, _downloadFile, value.zone),
        xpGained: value.xpGained,
        narration: value.narration,
        goldGained: value.goldGained,
        success: value.success,
        encounter: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.encounter))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    item: [] | [_Item];
    narration: string;
    success: boolean;
}): {
    item?: Item;
    narration: string;
    success: boolean;
} {
    return {
        item: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.item)),
        narration: value.narration,
        success: value.success
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    statBonus: _StatBonus;
    name: string;
    description: string;
    equipped: boolean;
    itemType: _ItemType;
    quantity: bigint;
}): {
    id: bigint;
    statBonus: StatBonus;
    name: string;
    description: string;
    equipped: boolean;
    itemType: ItemType;
    quantity: bigint;
} {
    return {
        id: value.id,
        statBonus: value.statBonus,
        name: value.name,
        description: value.description,
        equipped: value.equipped,
        itemType: from_candid_ItemType_n8(_uploadFile, _downloadFile, value.itemType),
        quantity: value.quantity
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Available: null;
} | {
    Active: null;
} | {
    Completed: null;
}): QuestStatus {
    return "Available" in value ? QuestStatus.Available : "Active" in value ? QuestStatus.Active : "Completed" in value ? QuestStatus.Completed : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Mage: null;
} | {
    Cleric: null;
} | {
    Rogue: null;
} | {
    Warrior: null;
}): Class {
    return "Mage" in value ? Class.Mage : "Cleric" in value ? Class.Cleric : "Rogue" in value ? Class.Rogue : "Warrior" in value ? Class.Warrior : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Elf: null;
} | {
    Orc: null;
} | {
    Dwarf: null;
} | {
    Human: null;
}): Race {
    return "Elf" in value ? Race.Elf : "Orc" in value ? Race.Orc : "Dwarf" in value ? Race.Dwarf : "Human" in value ? Race.Human : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Forest: null;
} | {
    Town: null;
} | {
    Mountains: null;
} | {
    Dungeon: null;
} | {
    Castle: null;
}): Zone {
    return "Forest" in value ? Zone.Forest : "Town" in value ? Zone.Town : "Mountains" in value ? Zone.Mountains : "Dungeon" in value ? Zone.Dungeon : "Castle" in value ? Zone.Castle : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Weapon: null;
} | {
    Potion: null;
} | {
    Misc: null;
} | {
    Armor: null;
}): ItemType {
    return "Weapon" in value ? ItemType.Weapon : "Potion" in value ? ItemType.Potion : "Misc" in value ? ItemType.Misc : "Armor" in value ? ItemType.Armor : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Item>): Array<Item> {
    return value.map((x)=>from_candid_Item_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quest>): Array<Quest> {
    return value.map((x)=>from_candid_Quest_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Character>): Array<Character> {
    return value.map((x)=>from_candid_Character_n28(_uploadFile, _downloadFile, x));
}
function to_candid_Class_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Class): _Class {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_ItemType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): _ItemType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_QuestStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestStatus): _QuestStatus {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_Race_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Race): _Race {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Zone_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Zone): _Zone {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): {
    Weapon: null;
} | {
    Potion: null;
} | {
    Misc: null;
} | {
    Armor: null;
} {
    return value == ItemType.Weapon ? {
        Weapon: null
    } : value == ItemType.Potion ? {
        Potion: null
    } : value == ItemType.Misc ? {
        Misc: null
    } : value == ItemType.Armor ? {
        Armor: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Race): {
    Elf: null;
} | {
    Orc: null;
} | {
    Dwarf: null;
} | {
    Human: null;
} {
    return value == Race.Elf ? {
        Elf: null
    } : value == Race.Orc ? {
        Orc: null
    } : value == Race.Dwarf ? {
        Dwarf: null
    } : value == Race.Human ? {
        Human: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Class): {
    Mage: null;
} | {
    Cleric: null;
} | {
    Rogue: null;
} | {
    Warrior: null;
} {
    return value == Class.Mage ? {
        Mage: null
    } : value == Class.Cleric ? {
        Cleric: null
    } : value == Class.Rogue ? {
        Rogue: null
    } : value == Class.Warrior ? {
        Warrior: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Zone): {
    Forest: null;
} | {
    Town: null;
} | {
    Mountains: null;
} | {
    Dungeon: null;
} | {
    Castle: null;
} {
    return value == Zone.Forest ? {
        Forest: null
    } : value == Zone.Town ? {
        Town: null
    } : value == Zone.Mountains ? {
        Mountains: null
    } : value == Zone.Dungeon ? {
        Dungeon: null
    } : value == Zone.Castle ? {
        Castle: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestStatus): {
    Available: null;
} | {
    Active: null;
} | {
    Completed: null;
} {
    return value == QuestStatus.Available ? {
        Available: null
    } : value == QuestStatus.Active ? {
        Active: null
    } : value == QuestStatus.Completed ? {
        Completed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
